name: Playwright C# Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet restore
      - run: dotnet build

      - name: Install Playwright
        run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

      - run: dotnet test